Fix/replace fetch records
KanasiOverflow/LainLot pull request #8
Opened 2024-07-28 18:45 UTC by LiubomyrVV

2024-07-28 18:50 UTC, KanasiOverflow requested changes
I'm waiting for changes

2024-07-28 18:50 UTC, KanasiOverflow commented on .gitignore
> +FodyWeavers.xsd
What's that?

2024-07-28 18:50 UTC, KanasiOverflow commented on Frontend/adminpanel/src/components/UI/button/GeneralButton.jsx
> -
Again, unnessecary changes

2024-07-28 18:59 UTC, KanasiOverflow requested changes

2024-07-28 18:59 UTC, KanasiOverflow commented on Frontend/adminpanel/src/context/ModalContext.jsx
> +            console.log(record, currentTable)
This mustn't be in the repo!

2024-07-28 18:59 UTC, KanasiOverflow commented on Frontend/adminpanel/src/pages/RecordIdPage.jsx
> +        console.log(fetchRecordById(params.table, params.id));
This mustn't be in the repo!

2024-07-28 18:59 UTC, KanasiOverflow commented on Frontend/adminpanel/src/pages/RecordIdPage.jsx
> -        fetchRecordById(params.table, params.id);
Why did you remove that?

2024-07-28 18:59 UTC, KanasiOverflow commented on Frontend/adminpanel/src/pages/RecordIdPage.jsx
>      useEffect(() => {
If this hook dont need it, it should be removed

2024-07-28 19:04 UTC, LiubomyrVV commented on Frontend/adminpanel/src/pages/RecordIdPage.jsx
>      useEffect(() => {
This part of the code is necessary

2024-07-28 19:05 UTC, KanasiOverflow requested changes

2024-07-28 19:05 UTC, KanasiOverflow commented on Frontend/adminpanel/src/pages/RecordIdPage.jsx
>      useEffect(() => {
For what? It's just console.log code

2024-07-31 08:46 UTC, KanasiOverflow approved these changes
Approve

2024-07-31 08:47 UTC, merged